-- | Equations shared by the CPU reference renderer and generated Metal code.
-- Swift owns input and presentation, never these material constants.
module HastellColor.Brush.Kernel
  ( BrushScalar
  , baseRadius, minorRadius, majorRadius, grainContact, strokeContact, depositAmount, raisedSurface
  , metalFunctions
  ) where

class Fractional a => BrushScalar a where
  saturate :: a -> a
  cosine :: a -> a

instance BrushScalar Double where
  saturate = max 0 . min 1
  cosine = cos

baseRadius :: BrushScalar a => a -> a -> a
baseRadius radius pressure = radius * (0.55 + 0.45 * pressure)

minorRadius, majorRadius :: BrushScalar a => a -> a -> a -> a
minorRadius radius pressure altitude = baseRadius radius pressure * (1 + 0.4 * cosine altitude)
majorRadius radius pressure altitude = baseRadius radius pressure * (1 + 2 * cosine altitude)

grainContact :: BrushScalar a => a -> a -> a -> a
grainContact height pressure edge =
  0.75 * pressure * edge * saturate ((height + 1.05 * pressure - 1) / 0.45)

strokeContact :: BrushScalar a => a -> a -> a
strokeContact contact strength = saturate (contact * strength)

depositAmount :: BrushScalar a => a -> a -> a
depositAmount amount contact = (1 - amount) * contact

raisedSurface :: BrushScalar a => a -> a -> a -> a
raisedSurface height amount nearby =
  height + (1 - height) * saturate (0.65 * amount + 1.6 * nearby)

-- A small expression language keeps GPU equations generated from the same
-- Haskell definitions as the Double implementation above.
newtype Shader = Shader String

binary :: String -> Shader -> Shader -> Shader
binary op (Shader a) (Shader b) = Shader ("(" ++ a ++ " " ++ op ++ " " ++ b ++ ")")

instance Num Shader where
  (+) = binary "+"
  (-) = binary "-"
  (*) = binary "*"
  negate (Shader a) = Shader ("(-" ++ a ++ ")")
  abs (Shader a) = Shader ("abs(" ++ a ++ ")")
  signum (Shader a) = Shader ("sign(" ++ a ++ ")")
  fromInteger n = Shader (show n ++ ".0f")

instance Fractional Shader where
  (/) = binary "/"
  fromRational n = Shader (show (fromRational n :: Double) ++ "f")

instance BrushScalar Shader where
  saturate (Shader a) = Shader ("saturate(" ++ a ++ ")")
  cosine (Shader a) = Shader ("cos(" ++ a ++ ")")

metalFunctions :: String
metalFunctions = unlines
  [ "// Generated by cabal run hastellcolor-metal. Do not edit."
  , "#include <metal_stdlib>"
  , "using namespace metal;"
  , function "hcBaseRadius(float r, float p)" (baseRadius r p)
  , function "hcMinorRadius(float r, float p, float a)" (minorRadius r p a)
  , function "hcMajorRadius(float r, float p, float a)" (majorRadius r p a)
  , function "hcGrainContact(float h, float p, float e)" (grainContact h p e)
  , function "hcStrokeContact(float c, float p)" (strokeContact c p)
  , function "hcDeposit(float m, float c)" (depositAmount m c)
  , function "hcSurface(float h, float m, float n)" (raisedSurface h m n)
  ]
  where
    r = Shader "r"
    p = Shader "p"
    a = Shader "a"
    h = Shader "h"
    e = Shader "e"
    m = Shader "m"
    c = Shader "c"
    n = Shader "n"
    function signature (Shader expression) = "float " ++ signature ++ " { return " ++ expression ++ "; }"
